# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~
        api_key_user_provider:
            id: app.security.webserviceuser_provider
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern: ^/api
            stateless: true
            simple_preauth:
                authenticator: app.security.apikey_authenticator
            provider: api_key_user_provider

    access_control:
            - { path: ^/api, roles: ROLE_API }
    encoders:
        AppBundle\Security\User\WebserviceUser: bcrypt
