# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.security.apikey_authenticator:
        class:  AppBundle\Security\ApiKeyAuthenticator
        public: false
    app.webserviceuser_repository:
        class: AppBundle\Repository\WebserviceUserRepository
        factory: ["@doctrine", "getRepository"]
        arguments:
            - AppBundle\Entity\WebserviceUser
    app.security.webserviceuser_provider:
        class: AppBundle\Security\WebserviceUserProvider
        arguments:
            - "@app.webserviceuser_repository"
